language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock
install:
    - ./gradlew :enderio-base:assemble
    - ./gradlew :enderio-machines:assemble
script:
    - ./gradlew :enderio-base:check
    - ./gradlew :enderio-machines:check